AWSTemplateFormatVersion: '2010-09-09'
Description: alblog to firehose test 20180506
Resources:
  Step1S3Bucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Delete
    Properties:
      LifecycleConfiguration:
        Rules:
          - Id: AutoDelete
            Status: Enabled
            ExpirationInDays: '7'
      NotificationConfiguration:
        TopicConfigurations:
          - Event: s3:ObjectCreated:*
            Filter:
              S3Key:
                Rules:
                  - Name: suffix
                    Value: gz
            Topic: !Ref 'Step2SnsTopic'
      VersioningConfiguration:
        Status: Enabled

  Step1S3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref 'Step1S3Bucket'
      PolicyDocument:
        Id: ElblogsBucketPolicy
        Statement:
          - Sid: AddPerm
            Effect: Allow
            Principal:
              AWS:
                - arn:aws:iam::582318560864:root
                - arn:aws:iam::127311923021:root
                - arn:aws:iam::033677994240:root
                - arn:aws:iam::027434742980:root
                - arn:aws:iam::797873946194:root
                - arn:aws:iam::985666609251:root
                - arn:aws:iam::054676820928:root
                - arn:aws:iam::156460612806:root
                - arn:aws:iam::652711504416:root
                - arn:aws:iam::156460612806:root
                - arn:aws:iam::009996457667:root
                - arn:aws:iam::600734575887:root
                - arn:aws:iam::383597477331:root
                - arn:aws:iam::114774131450:root
                - arn:aws:iam::797873946194:root
                - arn:aws:iam::783225319266:root
                - arn:aws:iam::718504428378:root
                - arn:aws:iam::507241528517:root
            Action:
              - s3:PutObject
            Resource:
              - !Join
                - ''
                - - 'arn:aws:s3:::'
                  - !Ref 'Step1S3Bucket'
                  - /*

  Step2SnsTopicPolicy:
    Type: AWS::SNS::TopicPolicy
    Properties:
      PolicyDocument:
        Version: '2012-10-17'
        Id: MyTopicPolicy
        Statement:
        - Sid: My-statement-id
          Effect: Allow
          Principal:
            Service:
            - s3.amazonaws.com
          Action:
          - sns:Publish
          Resource: !Ref 'Step2SnsTopic'
      Topics:
      - !Ref 'Step2SnsTopic'

  Step2SnsTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: trigger-elb-log-parse
      Subscription:
      - Endpoint: !GetAtt 'Step3LambdaFunction.Arn'
        Protocol: lambda

  Step3LambdaLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref 'Step3LambdaFunction'
      Action: lambda:InvokeFunction
      Principal: sns.amazonaws.com
      SourceArn: !Ref 'Step2SnsTopic'

  Step3LogGroupLambda:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/lambda/${Step3LambdaFunction}'
      RetentionInDays: 14

  Step3LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: root
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: '*'
              - Effect: Allow
                Action:
                  - sns:Publish
                Resource: '*'
              - Effect: Allow
                Action:
                  - s3:GetObject
                Resource: !Sub 'arn:aws:s3:::${AWS::StackName}-*'
              - Effect: Allow
                Action:
                  - firehose:PutRecordBatch
                Resource: !GetAtt 'Step3deliverystream.Arn'

  Step3LambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      Handler: index.lambda_handler
      Role: !GetAtt 'Step3LambdaRole.Arn'
      Code:
        ZipFile: !Sub |
          import boto3
          import json
          import os
          import urllib.parse
          import gzip
          from datetime import datetime
          import base64
          import re

          s3 = boto3.client('s3')
          firehose = boto3.client('firehose')

          def lambda_handler(event, context):
            #event2 is sns message
            event2 = json.loads(event['Records'][0]['Sns']['Message'])
            bucket_name = event2['Records'][0]['s3']['bucket']['name']
            key = urllib.parse.unquote_plus(event2['Records'][0]['s3']['object']['key'], encoding='utf-8')
            #print ('bucket_name: ' + bucket_name)
            #print ('key: ' + key)
            response =s3.get_object(Bucket=bucket_name, Key=key)
            body = gzip.decompress(response['Body'].read()).decode('utf-8').splitlines()
            process_log(body)

          def process_log(data):
            i = 0
            c = []
            for a in data:
              b = parse_log(a)
              if b is not None:
                c.append({'Data': b})
                i = i + 1
              if i == 100:
                PutRecordBatchFirehose(c)
                i = 0
                c = []
            if len(c) > 0:
              PutRecordBatchFirehose(c)

          def parse_log(line):
            z = {}
            a = line.split('"')
            b = a[0].split(' ')

            # Check ALB Log
            if len(b) == 13:
              if b[2].split('/')[0] == 'app':
                z["type"] = b[0]
                z["timestamp"] = b[1]
                z["elb"] = b[2]
                
                if len(b[3].split(':')) > 1:
                  z["client_port"] = b[3].split(':')[1]

                if len(b[4].split(':')) > 1:
                  z["target_port"] = b[4].split(':')[1]

                z["request_processing_time"] = float(b[5])
                z["target_processing_time"] = float(b[6])
                z["response_processing_time"] = float(b[7])
                z["elb_status_code"] = b[8]
                z["target_status_code"] = b[9]
                z["received_bytes"] = float(b[10])
                z["sent_bytes"] = float(b[11])

                z["request"] = a[1]
                z["user_agent"] = a[3]

                c = a[4].split(' ')
                if len(c) == 5:
                  z["ssl_cipher"] = c[1]
                  z["ssl_protocol"] = c[2]
                  z["target_group_arn"] = c[3]

                z["trace_id"] = a[5]
                z["domain_name"] = a[7]
                z["chosen_cert_arn"] = a[9]
                z["matched_rule_priority"] = a[10]

                if len(a) > 10:
                  d = a[10].split(' ')
                  if len(d) > 1:
                    z["matched_rule_priority"] = d[1]

                # fluent-plugin-elb-access-log compatible
                z["client"] = b[3].split(':')[0]
                z["target"] = b[4].split(':')[0]

                if len(z["request"].split(' ')) > 2:
                  z["request_method"] = z["request"].split(' ')[0]
                  z["request_uri"] = z["request"].split(' ')[1]
                  z["request_http_version"] = z["request"].split(' ')[2]

                  if z["request_method"] != '-' :
                    e = urllib.parse.urlparse(z["request_uri"])
                    z["request_uri_scheme"] = e.scheme
                    z["request_uri_user"] = e.username
                    z["request_uri_host"] = e.hostname
                    z["request_uri_port"] = e.port
                    z["request_uri_path"] = e.path
                    z["request_uri_query"] = e.query
                    z["request_uri_fragment"] = e.fragment

            #Column check (number, timestamp format)
            if len(z) > 4:
              if (re.match('[0-9]...-[0-9].-[0-9].T[0-9].:[0-9].:[0-9].\.[[0-9]*Z' , z["timestamp"])):
                #print(z)
                return json.dumps(z) + "\n"

          def PutRecordBatchFirehose(data):
            firehose_stream_name = os.environ['firehose_stream_name']
            r = firehose.put_record_batch(
              DeliveryStreamName = firehose_stream_name,
              Records = data
            )

            print(str(r["ResponseMetadata"]["HTTPHeaders"]))

      Runtime: python3.6
      MemorySize: 128
      Timeout: 300
      Description: ALB log S3(events) to firehose
      Environment:
        Variables:
          firehose_stream_name: !Ref 'Step3deliverystream'
      Tags:
        - Key: CloudformationArn
          Value: !Ref 'AWS::StackId'

  Step3deliverystream:
    DependsOn:
      - Step3deliveryPolicy
    Type: AWS::KinesisFirehose::DeliveryStream
    Properties:
      ExtendedS3DestinationConfiguration:
        BucketARN: !Sub 'arn:aws:s3:::${Step4S3bucket}'
        BufferingHints:
          IntervalInSeconds: '300'
          SizeInMBs: '10'
        CompressionFormat: GZIP
        Prefix: firehose/
        RoleARN: !GetAtt 'Step3deliveryRole.Arn'
        ProcessingConfiguration:
          Enabled: 'false'

  Step3deliveryRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: ''
            Effect: Allow
            Principal:
              Service: firehose.amazonaws.com
            Action: sts:AssumeRole
            Condition:
              StringEquals:
                sts:ExternalId: !Ref 'AWS::AccountId'

  Step3deliveryPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: firehose_delivery_policy
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - s3:AbortMultipartUpload
              - s3:GetBucketLocation
              - s3:GetObject
              - s3:ListBucket
              - s3:ListBucketMultipartUploads
              - s3:PutObject
            Resource:
              - !Sub 'arn:aws:s3:::${Step4S3bucket}'
              - !Sub 'arn:aws:s3:::${Step4S3bucket}*'
      Roles:
        - !Ref 'Step3deliveryRole'

  Step3LogGroupFirehose:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/firehose/${Step3deliverystream}'
      RetentionInDays: 7

  Step4S3bucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Delete
    Properties:
      LifecycleConfiguration:
        Rules:
          - Id: AutoDelete
            Status: Enabled
            ExpirationInDays: '40'
      NotificationConfiguration:
        TopicConfigurations:
          - Event: s3:ObjectCreated:*
            Filter:
              S3Key:
                Rules:
                  - Name: suffix
                    Value: gz
            Topic: !Ref 'Step5SnsTopic'

  Step5SnsTopicPolicy:
    Type: AWS::SNS::TopicPolicy
    Properties:
      PolicyDocument:
        Version: '2012-10-17'
        Id: MyTopicPolicy
        Statement:
        - Sid: My-statement-id
          Effect: Allow
          Principal:
            Service:
            - s3.amazonaws.com
          Action:
          - sns:Publish
          Resource: !Ref 'Step5SnsTopic'
      Topics:
      - !Ref 'Step5SnsTopic'

  Step5SnsTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: trigger-firehose-output-parse

  Step6LambdaLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref 'Step6LambdaFunction'
      Action: lambda:InvokeFunction
      Principal: sns.amazonaws.com
      SourceArn: !Ref 'Step5SnsTopic'

  Step6LogGroupLambda:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/lambda/${Step6LambdaFunction}'
      RetentionInDays: 14

  Step6LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: root
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: '*'
              - Effect: Allow
                Action:
                  - sns:Publish
                Resource: '*'
              - Effect: Allow
                Action:
                  - s3:GetObject
                Resource: !Sub 'arn:aws:s3:::${AWS::StackName}-*'
              - Effect: Allow
                Action:
                  - CloudWatch:PutMetricData
                Resource: '*'

  Step6LambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      Handler: index.lambda_handler
      Role: !GetAtt 'Step6LambdaRole.Arn'
      Code:
        ZipFile: !Sub |
          import boto3
          import json
          import os
          import urllib.parse
          import gzip
          from datetime import datetime
          import base64
          import re

          s3 = boto3.client('s3')
          cloudwatch = boto3.client('cloudwatch')

          def lambda_handler(event, context):
            #event2 is sns message
            event2 = json.loads(event['Records'][0]['Sns']['Message'])
            bucket_name = event2['Records'][0]['s3']['bucket']['name']
            key = urllib.parse.unquote_plus(event2['Records'][0]['s3']['object']['key'], encoding='utf-8')
            #bucket_name = 'a8-step4s3bucket-1c9do7ktxfccc'
            #key = 'firehose/2018/05/06/10/a8-Step3deliverystream-BKLUDM255VCW-3-2018-05-06-10-49-00-16e17fad-f2ff-44ce-b1be-e0cfc3576c6a.gz'
            
            #print ('bucket_name: ' + bucket_name)
            #print ('key: ' + key)
            response =s3.get_object(Bucket=bucket_name, Key=key)
            body = gzip.decompress(response['Body'].read()).decode('utf-8').splitlines()
            
            hosts = GetUniqRequestUriHost(body)

            for host in hosts:
              print ('host: '+ host)
              r = AggregateGroupbyRequestUriHost(body,host)

              #print(str(r))
              PutMetricData(r)


          def GetUniqRequestUriHost(data):
            d = []
            for a in data:
              b = json.loads(a)
              c = b['request_uri_host']
              if c not in d:
                d.append(c)
            return(d)

          def AggregateGroupbyRequestUriHost(data,host):

            total_received_bytes = 0
            total_sent_bytes = 0
            total_counts = 0
            z = {}

            for a in data:
              b = json.loads(a)
              if b['request_uri_host'] == host:
                total_received_bytes = total_received_bytes + b['received_bytes']
                total_sent_bytes = total_sent_bytes + b['sent_bytes']
                last_timestamp = b['timestamp']
                total_counts = total_counts + 1

            if total_counts > 0:
              z["total_received_bytes"] = total_received_bytes
              z["total_sent_bytes"] = total_sent_bytes
              z["total_counts"] = total_counts
              z["last_timestamp"] = datetime.strptime(last_timestamp, '%Y-%m-%dT%H:%M:%S.%fZ').replace(second=0, microsecond=0)
              z["request_uri_host"] = host

            return(z)

          def PutMetricData(data):

            last_timestamp =  data["last_timestamp"]
            request_uri_host = data["request_uri_host"]
            sample_count = data["total_counts"]
            total_sent_bytes = data["total_sent_bytes"]
            total_received_bytes = data["total_received_bytes"]
            
            CfnStackName = os.environ['CfnStackName']

            r = cloudwatch.put_metric_data(
              Namespace= 'ALB_LOG' ,
              MetricData=[
                {
                  'MetricName': 'sent_bytes',
                  'Dimensions':  [{'Name': 'request_uri_host','Value': request_uri_host}, {'Name': 'StackName','Value': CfnStackName}],
                  'Timestamp': last_timestamp,
                  'StatisticValues': {
                    'SampleCount': sample_count,
                    'Sum': total_sent_bytes,
                    'Minimum': total_sent_bytes,
                    'Maximum': total_sent_bytes,
                  },
                  'Unit': "Bytes"
                },
                {
                  'MetricName': 'received_bytes',
                  'Dimensions':  [{'Name': 'request_uri_host','Value': request_uri_host}, {'Name': 'StackName','Value': CfnStackName}],
                  'Timestamp': last_timestamp,
                  'StatisticValues': {
                    'SampleCount': sample_count,
                    'Sum': total_received_bytes,
                    'Minimum': total_received_bytes,
                    'Maximum': total_received_bytes,
                  },
                  'Unit': "Bytes"
                }
              ]
            )
        
      Runtime: python3.6
      MemorySize: 256
      Timeout: 300
      Description: ALB log (firehose output) to cloudwatch
      Environment:
        Variables:
          CfnStackName: !Sub '${AWS::StackName}'
      Tags:
        - Key: CloudformationArn
          Value: !Ref 'AWS::StackId'

